//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExifCleaner.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExifCleaner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Resulting files naming convention:.
        /// </summary>
        public static string BatchLblNaming {
            get {
                return ResourceManager.GetString("BatchLblNaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Other settings:.
        /// </summary>
        public static string BatchLblOther {
            get {
                return ResourceManager.GetString("BatchLblOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Source folder with images:.
        /// </summary>
        public static string BatchLblSource {
            get {
                return ResourceManager.GetString("BatchLblSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Target folder for cleaned images:.
        /// </summary>
        public static string BatchLblTarget {
            get {
                return ResourceManager.GetString("BatchLblTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Batch Metadata Removal.
        /// </summary>
        public static string BatchTitle {
            get {
                return ResourceManager.GetString("BatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ← Back to menu.
        /// </summary>
        public static string BtnBack {
            get {
                return ResourceManager.GetString("BtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Browse....
        /// </summary>
        public static string BtnBrowse {
            get {
                return ResourceManager.GetString("BtnBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Save cleaned copy.
        /// </summary>
        public static string BtnCleanSave {
            get {
                return ResourceManager.GetString("BtnCleanSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Open Image.
        /// </summary>
        public static string BtnOpenImage {
            get {
                return ResourceManager.GetString("BtnOpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Start Batch Cleaning.
        /// </summary>
        public static string BtnStartBatch {
            get {
                return ResourceManager.GetString("BtnStartBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Add random noise to all images (pixel anonymization).
        /// </summary>
        public static string ChkBatchNoise {
            get {
                return ResourceManager.GetString("ChkBatchNoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Use default /clean subfolder in source.
        /// </summary>
        public static string ChkDefaultTarget {
            get {
                return ResourceManager.GetString("ChkDefaultTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Add random noise on save.
        /// </summary>
        public static string ChkNoiseSingle {
            get {
                return ResourceManager.GetString("ChkNoiseSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Keep original name.
        /// </summary>
        public static string CmbNamingKeep {
            get {
                return ResourceManager.GetString("CmbNamingKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Add Prefix (before name).
        /// </summary>
        public static string CmbNamingPrefix {
            get {
                return ResourceManager.GetString("CmbNamingPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Add Suffix (after name).
        /// </summary>
        public static string CmbNamingSuffix {
            get {
                return ResourceManager.GetString("CmbNamingSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Metadata Key.
        /// </summary>
        public static string ColHeaderKey {
            get {
                return ResourceManager.GetString("ColHeaderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Value.
        /// </summary>
        public static string ColHeaderValue {
            get {
                return ResourceManager.GetString("ColHeaderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Batch folder cleaning.
        /// </summary>
        public static string HubBtnBatch {
            get {
                return ResourceManager.GetString("HubBtnBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný View and edit single image.
        /// </summary>
        public static string HubBtnSingle {
            get {
                return ResourceManager.GetString("HubBtnSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Select tool operation mode.
        /// </summary>
        public static string HubSubtitle {
            get {
                return ResourceManager.GetString("HubSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný File Metadata (Double-click to edit values).
        /// </summary>
        public static string MetadataHeader {
            get {
                return ResourceManager.GetString("MetadataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Processing files....
        /// </summary>
        public static string StatusProcessing {
            get {
                return ResourceManager.GetString("StatusProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Ready.
        /// </summary>
        public static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ExifCleaner // Minimalist Metadata Tool.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
